### ISSUE TITLE
Latest Unicode versions are missing

### ISSUE THREAD

**Issue by stof** [MadLittleMods/emoji-unicode-version#1]
As names are taken from emojione 2.2, the map does not support emoji from the latest Unicode versions.

**Comment by MadLittleMods** [comment]
@stof Which emoji are you looking for? Unicode 12? https://emojipedia.org/unicode-12.0/

Is there a better source we can pull all of that information from? We need the names of all emojis and their aliases.

Some ideas:

 - https://www.npmjs.com/package/emojilib
 - https://github.com/IonicaBizau/emoji-names

It's nice to stay in sync with emojione because [GitLab](https://gitlab.com/gitlab-org/gitlab-ce/blob/cf8c2eeba4fdf0f107aad312c09ab26eac04a29c/lib/tasks/gemojione.rake#L30-31) uses this package(`emoji-unicode-version`) and [`gemojione`](https://github.com/jonathanwiesel/gemojione). But this could also just be a verification step to make sure they are compatible

**Comment by stof** [comment]
but you currently stay in sync with emojione 2.2, which is years old. That means you don't support Unicode 11 either.

Making sure that names are compatible with emojione could indeed be a verification step if another source is used.

The data could also be taken from emojione 4.5 instead of 2.2 (and updating to newer releases once they support that), to get at least all codes supported by the current version of emojione.

**Comment by MadLittleMods** [comment]
@stof Feel free to make a pull request to update the `emojione` dependency

**Comment by MadLittleMods** [comment]
@stof Awesome! https://github.com/emojione/emojione/blob/79e685356877cbb6128074a71b7f88f435b58412/emoji.json


```
{
  "1f47d": {
    "name": "alien",
    "unicode_version": 6,
    "category": "people",
    "order": 1201,
    "display": 1,
    "shortname": ":alien:",
    "shortname_alternates": [
      
    ],
    "ascii": [
      
    ],
    "diversity": null,
    "diversities": [
      
    ],
    "gender": null,
    "genders": [
      
    ],
    "code_points": {
      "base": "1f47d",
      "fully_qualified": "1f47d",
      "non_fully_qualified": "1f47d",
      "output": "1f47d",
      "default_matches": [
        "1f47d",
        "1f47d-fe0f"
      ],
      "greedy_matches": [
        "1f47d",
        "1f47d-fe0f"
      ],
      "decimal": ""
    },
    "keywords": [
      "creature",
      "extraterrestrial",
      "face",
      "fairy tale",
      "fantasy",
      "monster",
      "ufo"
    ]
  }
}
```

---

As an aside, it looks like [`gemojione` doesn't have this info yet](https://github.com/jonathanwiesel/gemojione/blob/9c18b72ad0c1b50e46aa132f755b7f98b218e1f2/config/index.json) so still need this package for GitLab

**Comment by stof** [comment]
> As an aside, it looks like [`gemojione` doesn't have this info yet](https://github.com/jonathanwiesel/gemojione/blob/9c18b72ad0c1b50e46aa132f755b7f98b218e1f2/config/index.json) so still need this package for GitLab

here is the reason: https://github.com/jonathanwiesel/gemojione/issues/54#issuecomment-457043045
